The default Milano shell is bourne
...not Bourne-Again Shell.

diff --git a/shipit.yml b/shipit.yml
--- a/shipit.yml
+++ b/shipit.yml
@@ -5,22 +5,24 @@ deploy:
   max_commits: # Automatically deploy all commits, no matter how many.
   override:
     - |
-      #! /usr/bin/env bash
-      pids=()
+      pids=""
+
       bin/deployer bash -lc "id=wumpus bin/deploy" &
-      pids+=($!)
+      pids="${pids} $!"
+
       bin/deployer bash -lc "id=boom bin/deploy" &
-      pids+=($!)
+      pids="${pids} $!"
+
       bin/deployer bash -lc "id=bumpus bin/deploy" &
-      pids+=($!)
-      status=0
-      echo "pids: ${pids[*]}"
-      for pid in ${pids[*]}
+      pids="${pids} $!"
+
+      errors=0
+      for pid in ${pids}
       do
-        wait "$pid" || (( status+=1 ))
+          wait "${pid}" || errors=1
       done
-      echo "Status:  $status"
-      exit $status
+
+      echo "# Status: ${errors}"
 
 tasks:
   restart:
